# Generated by Django 5.1.3 on 2024-12-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
